# Generated by Django 5.0.6 on 2024-07-02 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='DayWiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_0800', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_1000', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_1200', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_1400', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_1600', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_1800', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_2000', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_2200', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_0000', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_0200', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_0400', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_app.subcategory')),
            ],
        ),
    ]
