# Generated by Django 5.0.4 on 2024-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0003_daywisedata_time_0100_daywisedata_time_0300_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywisedata',
            name='reason',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
