# Generated by Django 5.0.4 on 2024-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0004_daywisedata_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywisedata',
            name='input',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
